runtime: java21
entrypoint: 'java -jar server-all.jar'
env_variables:
  ktor_mongo_uri: 'mongodb+srv://ktor_client:0S0VYnc43I5lFOf1@lt-internal-main.vi9km.mongodb.net/?retryWrites=true&w=majority&appName=lt-internal-main'


